version: "3"

services:
  mysqlapp:
    container_name: mysqlapp
    image: mysql:5.7
    ports:
      - "6603:3306"
    env_file:
      - .dockerenv

  web:
    container_name: webApp
    build:
      context: .
      dockerfile: container-build/web/Dockerfile
    env_file:
      - .dockerenv
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - mysqlapp

  phpmyadmin:
    depends_on:
      - mysqlapp
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8989:80
    env_file:
      - .dockerenv

volumes:
  mysql_data: { driver: local }
